<a href="https://colab.research.google.com/github/cosraj/hashicat-aws/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Array indexing

In [ ]:
arr1 = np.arange(0,11)
arr1
np.sum(arr1)
arr1[8:]

array([ 8,  9, 10])

np.reshape() is a useful method for reshaping arrays

In [ ]:
arr = np.random.randint(0,25,10
                        )

In [ ]:
arr

array([ 3, 11, 14, 13, 22,  3, 16, 14,  2, 10])

In [ ]:
arr.reshape(2,5)
arr.max()
arr.argmax()

4

np.eye() method returns the identity matrix

In [ ]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
arr2 = np.arange(0,10)
print("Original Array",arr2)
slice_arr2 = arr2[0:5]
print("Slice array",slice_arr2)
slice_arr2[:] = 100
print("Slice array after broadcast",slice_arr2)
print("Original array also impacted by broadcasing ",arr2)
arr3 = np.arange(0,10)
print("another original array", arr3)
arr3_copy = arr3.copy()
print("copy of arr3", arr3_copy)
arr3[:] = 100
print("Original array after broadcast", arr3)
print("Copy is not changed due to broadcast ",arr3_copy)

Original Array [0 1 2 3 4 5 6 7 8 9]
Slice array [0 1 2 3 4]
Slice array after broadcast [100 100 100 100 100]
Original array also impacted by broadcasing  [100 100 100 100 100   5   6   7   8   9]
another original array [0 1 2 3 4 5 6 7 8 9]
copy of arr3 [0 1 2 3 4 5 6 7 8 9]
Original array after broadcast [100 100 100 100 100 100 100 100 100 100]
Copy is not changed due to broadcast  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
print("2D array", arr_2d)
print(arr_2d[:2,1:])

2D array [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[10 15]
 [25 30]]


In [ ]:
arr4 = np.arange(0,25,5)
print(arr4)
arr5 = arr4[arr4 < 10]
print(arr5)

[ 0  5 10 15 20]
[0 5]


In [ ]:
arr5 = np.arange(0,10)
print(arr5)
arr6 = arr5 * 5
print("Multiplying an array with a scalar ",arr6)
print("Multiplying an array with itself",arr5 * arr5)

[0 1 2 3 4 5 6 7 8 9]
Multiplying an array with a scalar  [ 0  5 10 15 20 25 30 35 40 45]
Multiplying an array with itself [ 0  1  4  9 16 25 36 49 64 81]
