<a href="https://colab.research.google.com/github/cosraj/hashicat-aws/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.arange(0,10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Array indexing

In [ ]:
arr1 = np.arange(0,11)
arr1
np.sum(arr1)
arr1[8:]

array([ 8,  9, 10])

np.reshape() is a useful method for reshaping arrays

In [ ]:
arr = np.random.randint(0,25,10
                        )

In [ ]:
arr

array([ 3, 11, 14, 13, 22,  3, 16, 14,  2, 10])

In [ ]:
arr.reshape(2,5)
arr.max()
arr.argmax()

4

np.eye() method returns the identity matrix

In [ ]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
arr2 = np.arange(0,10)
print("Original Array",arr2)
slice_arr2 = arr2[0:5]
print("Slice array",slice_arr2)
slice_arr2[:] = 100
print("Slice array after broadcast",slice_arr2)
print("Original array also impacted by broadcasing ",arr2)
arr3 = np.arange(0,10)
print("another original array", arr3)
arr3_copy = arr3.copy()
print("copy of arr3", arr3_copy)
arr3[:] = 100
print("Original array after broadcast", arr3)
print("Copy is not changed due to broadcast ",arr3_copy)

Original Array [0 1 2 3 4 5 6 7 8 9]
Slice array [0 1 2 3 4]
Slice array after broadcast [100 100 100 100 100]
Original array also impacted by broadcasing  [100 100 100 100 100   5   6   7   8   9]
another original array [0 1 2 3 4 5 6 7 8 9]
copy of arr3 [0 1 2 3 4 5 6 7 8 9]
Original array after broadcast [100 100 100 100 100 100 100 100 100 100]
Copy is not changed due to broadcast  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
print("2D array", arr_2d)
print(arr_2d[:2,1:])

2D array [[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[[10 15]
 [25 30]]


In [ ]:
arr4 = np.arange(0,25,5)
print(arr4)
arr5 = arr4[arr4 < 10]
print(arr5)

[ 0  5 10 15 20]
[0 5]


In [ ]:
arr5 = np.arange(0,10)
print(arr5)
arr6 = arr5 * 5
print("Multiplying an array with a scalar ",arr6)
print("Multiplying an array with itself",arr5 * arr5)

[0 1 2 3 4 5 6 7 8 9]
Multiplying an array with a scalar  [ 0  5 10 15 20 25 30 35 40 45]
Multiplying an array with itself [ 0  1  4  9 16 25 36 49 64 81]


Udemy exerices for Pandas

In [ ]:
import numpy as np

In [ ]:
zarray = np.zeros(10)
print(zarray)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
array1 = np.ones(10)
print(array1)
array5 = array1*5
print(array5)
print(array1)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
array2 = np.arange(10,51)
print(array2)
arrayeven = array2[array2%2 == 0]
print(arrayeven)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
array3by3 = np.arange(0,9).reshape(3,3)
print(array3by3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
ident = np.eye(3,3)
print(ident)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
np.random.rand(1)

array([0.85594182])

Generate 25 numbers from a sample random distribution

In [ ]:
print(np.random.randn(25))

[ 2.44656899e-01  4.43495339e-01 -1.38567181e+00 -4.99212206e-01
 -6.42057013e-01  2.46062441e+00  8.02735994e-01  8.86233593e-01
 -7.70937958e-01 -7.63179624e-01 -1.27834148e+00 -1.81778003e-01
  1.32832741e+00 -3.15389009e-01 -1.07424279e+00 -2.35920323e-01
  7.68387474e-01 -9.78307949e-01 -1.63296425e+00 -1.05589647e+00
 -2.13468537e+00 -9.24032853e-01 -6.87616396e-01 -3.64266436e-01
  6.66295633e-04]


In [ ]:
print(np.arange(0.01,1.01,0.01).reshape(10,10))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


Using linspace instead of arange

In [ ]:
print(np.linspace(0.01,1,100).reshape(10,10))

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
print(np.linspace(0,1,20))

[0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


In [8]:
mat = np.arange(1,26).reshape(5,5)
print(mat)
print(mat[2:,1:])
print(mat[3,4])


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]
20
